import {Clubs, Reservation} from '../modules/statistic/types/StatisticTypes.ts';

export const db: {clubs: Reservation[]; clubHome: Clubs[]} = {
  clubs: [
    {
      id: '1',
      image: require('../assets/images/image/club/yaradiciliq2.jpg'),
      date: '2024-03-18T00:00:00.000Z',
      name: 'Natiqlik Klubu',
      datee: 'Ç, 18 mart, 2024, 15:00',
      bgColor: '#DBF3FF',
      progresColor: '#C2E3E8',
      color: '#5A5A5A',
      nameColor: '#757575',
      center: '5 saylı Bakı DOST Mərkəzi',
      topic:
        '"Natiqlik" klubunda qonağımız olacaq Coşqun Kərimov yazıçı və natiqlik üzrə kouçdur.',
      text:
        '"Natiqlik" klubunda qonağımız olacaq Coşqun Kərimov yazıçı və natiqlik üzrə kouçdur. \n' +
        '10 ildən çoxdur ki, dövlət və özəl təşkilat rəhbərlərinə, sahibkar və mütəxəssislərə yerli və beynəlxalq tədbirlərdə effektiv şəkildə çıxış etməyə kömək edir. Həmçinin dünyaca məşhur təlimçi və müəllif olan Brayan Treysinin şəxsi inkişaf üçün tövsiyyə etdiyi KVAN kitabının müəllifidir.🧐',
    },
    {
      id: '2',
      image: require('../assets/images/image/club/yaradiciliq3.jpeg'),
      date: '2024-03-19T00:00:00.000Z',
      name: 'Yaradıcılıq',
      datee: 'Ç, 19 mart, 2024, 14:30',
      bgColor: '#9EFFBE',
      progresColor: '#00FF55',
      color: '#000',
      nameColor: '#757575',
      center: '4 saylı Bakı DOST Mərkəzi',
      topic:
        '"Yaradıcılıq" klubunda Torpaq çərşənbəsi münasibətilə "Eggcellent Artistry" adlı yumurta bəzədilməsi master-klası olacaq.',
      text: '"Yaradıcılıq" klubunda Torpaq çərşənbəsi münasibətilə "Eggcellent Artistry" adlı yumurta bəzədilməsi master-klası olacaq.Sonda isə Azərbaycanın qədim oyunlarından olan "Yumurta döyüşdürmə" oyunu oynanılacaq. 🥚',
    },
    {
      id: '3',
      image: require('../assets/images/image/club/yaradiciliq.jpeg'),
      date: '2024-03-19T00:00:00.000Z',
      name: 'Xarici dil',
      datee: 'C, 19 mart, 2024, 12:00',
      bgColor: '#FC714E',
      progresColor: '#D25600',
      color: '#fff',
      nameColor: '#fff',
      center: '5 saylı Bakı DOST Mərkəzi',
      topic:
        '"Dream Language School" İnglis dili kursunun rəhbəri Gülnar Baxşəliyeva "Easiest ways to learn English" adlı təlim keçəcək.',
      text: 'Xarici Dil klubunda "Dream Language School" İnglis dili kursunun rəhbəri Gülnar Baxşəliyeva "Easiest ways to learn English" adlı təlim keçəcək.✌️',
    },
  ],
  clubHome: [
    {
      id: 1,
      text: 'Yaradıcılıq',
      bgColor: '#2858EE',
      colors: '#2858EE18',
      image: require('../assets/images/image/club/ferdi.png'),
    },
    {
      id: 2,
      text: 'Xarici dil',
      bgColor: '#DDA2E6',
      colors: '#DBA1E428',
      image: require('../assets/images/image/club/xariciDil.png'),
    },
    {
      id: 3,
      text: 'Kitab',
      bgColor: '#FE5024',
      colors: '#FE502428',
      image: require('../assets/images/image/club/kitab.png'),
    },
    {
      id: 4,
      text: 'Film',
      bgColor: '#E64646',
      colors: '#E6464628',
      image: require('../assets/images/image/club/filim.png'),
    },
    {
      id: 5,
      text: 'Şahmat',
      bgColor: '#DA78A7',
      colors: '#DA78A728',
      image: require('../assets/images/image/club/sahmat.png'),
    },
    {
      id: 6,
      text: 'Layihələr',
      bgColor: '#006554',
      colors: '#00655428',
      image: require('../assets/images/image/club/lahieler.png'),
    },
    {
      id: 7,
      text: 'Fərdi inkişaf',
      bgColor: '#E69800',
      colors: '#E6980028',
      image: require('../assets/images/image/club/ferdiinksad.png'),
    },
    {
      id: 8,
      text: 'Tarix',
      bgColor: '#E62900',
      colors: '#E6290028',
      image: require('../assets/images/image/club/tarix.png'),
    },
    {
      id: 9,
      text: 'Natiqlik',
      bgColor: '#7311D2',
      colors: '#7311D228',
      image: require('../assets/images/image/club/natiqlik.png'),
    },
    {
      id: 10,
      text: 'Oyunlar',
      bgColor: '#B98A40',
      colors: '#B98A4028',
      image: require('../assets/images/image/club/oyunlar.png'),
    },
    {
      id: 11,
      text: 'Səyahətçilər',
      bgColor: '#E6AFA2',
      colors: '#E6AFA228',
      image: require('../assets/images/image/club/seyahetciler.png'),
    },
    {
      id: 12,
      text: 'Şeir',
      bgColor: '#E64646',
      colors: '#E6464618',
      image: require('../assets/images/image/club/vector.png'),
    },
  ],
};
